export const NOTIFICATION_TYPES = {
  PURCHASE_REQUEST: "PURCHASE_REQUEST",
  REQUEST_SENT: "REQUEST_SENT",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  REQUEST_DECLINED: "REQUEST_DECLINED",
  LISTING_EXCHANGED: "LISTING_EXCHANGED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  REVIEW_REMINDER: "REVIEW_REMINDER",
  SELLER_REPORTED: "SELLER_REPORTED",
  NEW_CHAT: "NEW_CHAT",
  NEW_MESSAGE: "NEW_MESSAGE",
};
